### add a new car

POST http://localhost:3000/reports
content-type: application/json

{
    "make": "chevy",
    "model": "camaro",
    "year": 1984,
    "mileage": 105300,
    "lng": 0,
    "lat": 0,
    "price": 1250
}

### approve an existing report

PATCH http://localhost:3000/reports/3
content-type: application/json

{
    "approved": true
}

### un-approve a report

PATCH http://localhost:3000/reports/3
content-type: application/json

{
    "approved": false
}